# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(332, 181)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        widget.setFont(font)
        widget.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"font: 75 12pt \"Times New Roman\";\n"
"font: 75 12pt \"宋体\";")
        self.label = QtWidgets.QLabel(widget)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(30, 17, 41, 31))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(31, 75, 41, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(widget)
        self.pushButton.setGeometry(QtCore.QRect(80, 140, 211, 31))
        self.pushButton.setStyleSheet("background-color: rgb(120, 172, 255);\n"
"font: 75 12pt \"Times New Roman\";\n"
"font: 75 12pt \"宋体\";")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(widget)
        self.lineEdit.setGeometry(QtCore.QRect(78, 14, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(79, 75, 211, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(widget)
        self.checkBox.setGeometry(QtCore.QRect(80, 112, 111, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "分项计量用户登录"))
        self.label.setText(_translate("widget", "账号"))
        self.label_2.setText(_translate("widget", "密码"))
        self.pushButton.setText(_translate("widget", "登录"))
        self.checkBox.setText(_translate("widget", "记住密码"))
