# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_UI_QMainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1259, 841)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(3, 11, 30);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"font: 17pt \"黑体\";\n"
"color: rgb(110, 255, 207);\n"
"border: 4px solid rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0.1);\n"
"border-radius:15px")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"font: 17pt \"黑体\";\n"
"color: rgb(110, 255, 207);\n"
"border: 4px solid rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0.1);\n"
"border-radius:15px")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"font: 17pt \"黑体\";\n"
"color: rgb(110, 255, 207);\n"
"border: 4px solid rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0.1);\n"
"border-radius:15px")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"font: 17pt \"黑体\";\n"
"color: rgb(110, 255, 207);\n"
"border: 4px solid rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0.1);\n"
"border-radius:15px")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "亿为分项计量"))
        self.pushButton_4.setText(_translate("MainWindow", "电量统计分析"))
        self.pushButton_8.setText(_translate("MainWindow", "统计汇总表"))
        self.pushButton_5.setText(_translate("MainWindow", "分时时段配置"))
        self.pushButton_7.setText(_translate("MainWindow", "站点配置与抄表"))
